name: Create artifact

on:
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, test, and create artifact
      run: |
        npm ci
        npm test
        npm run dist
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tikzcd-editor
        path: ./dist/tikzcd-editor
