name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm test -- --reporter=base
      env:
        CI: true

    - name: Create artifact
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npm run dist
        rm -rf ./dist/tikzcd-editor
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: tikzcd-editor-dist
        path: ./dist
