name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm test -- --reporter=base

  create-artifact:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Extract tag name & ci path
      id: info
      run: |
        node -e "console.log('::set-output name=tag::' + process.env.GITHUB_REF.replace('refs/tags/', ''))"
        node -e "console.log('::set-output name=ci::' + require('path').resolve(process.cwd(), './ci'))"
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Create artifact
      run: |
        npm ci
        npm run dist
    - name: Upload artifact
      run: |
        go get -u github.com/tcnksm/ghr
        ./ci/bin/ghr -n "tikzcd-editor ${{ steps.info.outputs.tag }}" -draft ${{ steps.info.outputs.tag }} ./dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ steps.info.outputs.ci }}
